name: device_safety_info
description: Device Safety Info Flutter Plugin used for checking JailBreak, Rooted Device, Emulator/Simulator, External storage, VPN Detector, Application Update Checker and Screen Lock.
version: 1.0.4
homepage: https://github.com/devamitkumartiwari/devicesafetyinfo

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  package_info_plus: ^9.0.0
  http: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any



flutter:

  plugin:
    platforms:
      android:
        package: com.devamitkumartiwari.device_safety_info
        pluginClass: DeviceSafetyInfoPlugin
      ios:
        pluginClass: DeviceSafetyInfoPlugin

